CREATE TABLE IF NOT EXISTS pipeline_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_id CHAR(36) NOT NULL,
    step_number INT NOT NULL,
    step_name VARCHAR(100) NULL,
    status VARCHAR(30) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    error_reason VARCHAR(1000) NULL,
    exception_type VARCHAR(500) NULL,
    exception_message TEXT NULL,
    stack_trace LONGTEXT NULL,
    host_name VARCHAR(255) NULL,
    user_name VARCHAR(255) NULL,
    ip_address VARCHAR(45) NULL,
    service_name VARCHAR(255) NULL,
    service_version VARCHAR(50) NULL,
    process_id INT NULL,
    file_name VARCHAR(500) NULL,
    file_path VARCHAR(2000) NULL,
    file_size BIGINT NULL,
    file_hash CHAR(64) NULL,
    attempt_number INT NULL,
    occurred_at DATETIME(3) NOT NULL,
    metadata_json JSON NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_pipeline_logs_event_id (event_id),
    KEY ix_pipeline_logs_step_status (step_number, status),
    KEY ix_pipeline_logs_occurred_at (occurred_at),
    KEY ix_pipeline_logs_file_hash (file_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;