CREATE TABLE IF NOT EXISTS azure_file_copies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    transaction_id CHAR(36) NOT NULL,
    file_hash CHAR(64) NOT NULL,
    file_name VARCHAR(500) NOT NULL,
    local_path VARCHAR(2000) NOT NULL,
    remote_path VARCHAR(2000) NOT NULL,
    status VARCHAR(30) NOT NULL,
    attempt_number INT NOT NULL,
    file_length BIGINT NULL,
    local_md5 CHAR(32) NULL,
    remote_md5 CHAR(32) NULL,
    host_name VARCHAR(255) NULL,
    user_name VARCHAR(255) NULL,
    created_at DATETIME(3) NOT NULL,
    completed_at DATETIME(3) NULL,
    next_attempt_at DATETIME(3) NULL,
    last_error LONGTEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_azure_file_copy_transaction (transaction_id),
    KEY ix_azure_file_copy_hash_status (file_hash, status),
    KEY ix_azure_file_copy_retry (status, next_attempt_at),
    KEY ix_azure_file_copy_remote_path (remote_path)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
